# Generated by Django 5.1.1 on 2024-10-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
