# Generated by Django 5.1.1 on 2024-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
