# Generated by Django 5.1.1 on 2024-11-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='news.newscategory'),
        ),
    ]
