# Generated by Django 5.1.1 on 2024-11-05 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newsarticle_category_newsarticle_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='left_coverage_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='right_coverage_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='total_sources',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lopsidedstory',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lopsided_story', to='news.newsarticle'),
        ),
    ]
