# Generated by Django 5.1.1 on 2024-11-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_left_coverage_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='bias',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='center', max_length=10),
        ),
    ]
