# Generated by Django 5.1.1 on 2024-11-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newssource_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='lopsidedstory',
            name='center_coverage_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
