# Generated by Django 5.1.1 on 2024-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_lopsidedstory_center_coverage_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssource',
            name='bias',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_negative',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_positive',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LopsidedStory',
        ),
    ]
