# Generated by Django 5.1.1 on 2024-11-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newssource_bias_newsarticle_sentiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='left_coverage_percentage',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='right_coverage_percentage',
        ),
    ]
